# Generated by Django 2.1.2 on 2018-11-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adopcionperro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePerroAdop', models.CharField(max_length=40)),
                ('CorreoAdop', models.CharField(max_length=50)),
                ('RutAdop', models.CharField(max_length=60)),
                ('DireccionAdop', models.CharField(max_length=9)),
                ('TelefonoAdop', models.CharField(max_length=20)),
            ],
        ),
    ]
