# Generated by Django 2.1.2 on 2018-11-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioPersona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariopersona',
            name='Direccion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formulariopersona',
            name='NombreCompleto',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='formulariopersona',
            name='Telefono',
            field=models.CharField(max_length=9),
        ),
    ]
