# Generated by Django 2.1.2 on 2018-10-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePerro', models.CharField(max_length=40)),
                ('Raza', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('EstadoPerro', models.CharField(choices=[('1', 'Rescatado'), ('2', 'Adoptado'), ('3', 'Disponible')], max_length=40)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='validacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.formularios')),
            ],
        ),
    ]
